
image: amazonlinux:latest
    



stages:
  - init
  - plan
  - apply
  - destroy

variables:
  AWS_REGION: "us-west-2"  # Change 
  

 # TF_STATE_BUCKET: "my-terraform-bucket"  # Remote state S3 bucket
 # TF_STATE_KEY: "eks-cluster/terraform.tfstate"

before_script:
  - yum update -y
  - yum install -y sudo unzip  

  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

  - yum install -y unzip wget
  - sudo yum install -y yum-utils 
  -  sudo mkdir -p /usr/share/keyrings

  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  -  sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - sudo yum install terraform -y
  - pwd
  - cd EKS-VPC
  - ls -la

  - terraform --version  # Verify installation

terraform-init:
  stage: init
  script:
    - terraform init 
    - terraform validate
 
terraform-plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  dependencies:
    - terraform-init
  
terraform-apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform-plan
  when: manual  # Requires manual approval before applying
terraform-destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve tfplan
  dependencies:
    - terraform-apply
  when: manual  # Requires manual approval before applying
  
