
image:
    name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'



stages:
  - init
  - plan
  - apply
  - destroy

variables:
  AWS_REGION: "us-west-2"  # Change 
  

 # TF_STATE_BUCKET: "my-terraform-bucket"  # Remote state S3 bucket
 # TF_STATE_KEY: "eks-cluster/terraform.tfstate"

before_script:
  - yum update -y
  - yum install -y sudo unzip  

  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

  - yum install -y unzip wget
  - wget https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)_linux_amd64.zip

  - unzip terraform_1.6.0_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - pwd
  - cd EKS-VPC
  - ls -la

  - terraform --version  # Verify installation

terraform-init:
  stage: init
  script:
    - terraform init 
    - terraform validate
 
terraform-plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  dependencies:
    - terraform-init
  
terraform-apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform-plan
  when: manual  # Requires manual approval before applying
terraform-destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve tfplan
  dependencies:
    - terraform-apply
  when: manual  # Requires manual approval before applying
  
